
const palya1 = [
    [{color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#000000", text:"1", count: 0},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""}],
    
    [{color: "#ffffff", text:""},
    {color: "#000000", text:"0", count: 0},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#000000", text:"2", count: 0},
    {color: "#ffffff", text:""}],
    
    [{color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""}],
    
    [{color: "#000000", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#000000", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#000000", text:""}],
    
    [{color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""}],
    
    [{color: "#ffffff", text:""},
    {color: "#000000", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#000000", text:"2", count: 0},
    {color: "#ffffff", text:""}],
    
    [{color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#000000", text:"3", count: 0},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""},
    {color: "#ffffff", text:""}]];

const palya2 = [
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"0", count: 0},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""}
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"3", count: 0},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""}
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"1", count: 0},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#000000", text:"2", count: 0},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"2", count: 0},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ]
];

const palya3 = [
    [
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"3", count: 0},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"2", count: 0},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#000000", text:"0", count: 0},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#000000", text:"1", count: 0},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#000000", text:"1", count: 0},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#000000", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"3", count: 0},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"1", count: 0},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"0", count: 0},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#000000", text:"3", count: 0},
        {color: "#ffffff", text:""},
        {color: "#000000", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"0", count: 0},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
    ],
    [
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#ffffff", text:""},
        {color: "#000000", text:"0", count: 0},
        {color: "#ffffff", text:""},
    ],
];